#!/bin/sh

make lint-git

STAGED_MOVE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.move$')

echo $STAGED_MOVE_FILES
npx prettier-move $STAGED_MOVE_FILES --write
git add $STAGED_MOVE_FILES
