name: SuiMove

permissions:
  contents: read
  pull-requests: write

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - '**.move'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-tools:ci
    strategy:
      matrix:
        working-directory:
          - packages/bitcoin_spv
          - packages/bitcoin_parser
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: sui move build
      - name: Run test
        # set more gas when run test with flag -i
        run: sui move test -i 5000000
      # Enable when support --coverage flag in sui-tools docker
      # - name: coverage test
      #   run:  sui move test --coverage
      # - name: Check test coverage
      #   run:  echo "check test coverage range"

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # @v2
      - uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2
      - run: bun install @mysten/prettier-plugin-move

      - run: bun prettier-move --config .prettier-move.json -c **/*.move
