name: Move Tests

on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-tools:ci
    strategy:
      matrix:
        working-directory:
          - packages/bitcoin_spv
          - packages/bitcoin_parser
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: sui move build
      - name: Run test
        # set more gas when run test with flag -i
        run: sui move test -i 5000000
      # Enable when support --coverage flag in sui-tools docker
      # - name: coverage test
      #   run:  sui move test --coverage
      # - name: Check test coverage
      #   run:  echo "check test coverage range"
